print('= ' * 30, f'\n{'DESAFIO 22 - NOMES':^60}')
print('= ' * 30)
nome = str(input('\nDigite o seu nome completo: ')).strip()
n = nome.split()
print(f'O seu nome é {nome}.')
print(f'Seu nome com letras maiúsculas é {nome.upper()}.')
print(f'Seu nome com letras minúsculas é {nome.lower()}.')
print(f'Ao todo seu nome tem {len(''.join(n))} letras.')  #format(len(nome) - nome.count(' '))
print(f'Seu primeiro nome é {n[0]} e ele tem {len(n[0])} letras.\n')  #format(nome.find(' ')
print('= ' * 31)
